
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vegetable-project
    username: root
    password: 01229050402a
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hoangquanph0204@gmail.com
    password: hspuorvvliiqgbgr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

